### ISSUE TITLE
Navegacion pierde filtros

### ISSUE THREAD

**Issue by neurus1970** [neurus1970/sam#3]
Al invocar a la URI

/sam/tickets/environment/country?severity=P1

arroja la siguiente estructura (ejemplo)
  "environments": [
    {
      "count": 17,
      "URI": "/sam/_search/tickets?environment=CERT",
      "environment": "Certification",
      "countries": [
        {
          "URI": "/sam/_search/tickets?environment=CERT&country=BR",
          "count": 14,
          "country": "Brazil"
        }
      ]
    }...

Donde se ha perdido el filtro de "severity=P1"

debería ser:

/sam/_search/tickets?environment=CERT&country=BR&severity=P1

**Comment by ABFenix** [comment]
OKIS... Lo tengo en cuenta...
