### ISSUE TITLE
Valores del campo "environment"

### ISSUE THREAD

**Issue by ManuelLop** [neurus1970/sam#6]
el campo entorno vuelve a mostrar los valores CERT, PRO

Entiendo que estos valores son para poder construir la URI de una forma más sencilla, pero para mostrar los datos por pantalla es necesaria la descripción completa

No sería más sencillo disponer de dos campos, uno con la descripción corta para utilizarlo en la URI y otro con la descripción larga.

**Comment by neurus1970** [comment]
Hola Manuel, me podrías pasar un ejemplo?

En local cuando lo ejecuto me devuelve el country.code y country.name como habíamos acordado.

Tal vez sea solo un problema de nivelación y necesite subir la version que tengo en local.

Te envío un correo con la captura de pantalla y dime si así como se ve en mi captura es lo que esperabas ver.

un saludo.

**Comment by neurus1970** [comment]
Era un problema de parametrización (no de código) estaba mal escrito el parámetro "translatable" en las propiedades del "country" y del "environment"
Ya funciona correctamente.
